#!/usr/bin/env bun
/**
 * Build-time script: reads all files from the root templates/ directory and
 * outputs src/config/templates.ts as an embedded TypeScript module.
 * Also builds the Invoke.SDK NuGet package and embeds it as base64.
 *
 * Output shape:
 *   export const TEMPLATES: Record<string, Record<string, string>> = {
 *     'bun-typescript-function': { 'index.ts': '...', 'package.json': '...' },
 *     ...
 *   }
 */

import { execSync } from 'child_process'
import fs from 'fs'
import os from 'os'
import path from 'path'

const TEMPLATES_DIR = path.resolve(__dirname, '../../templates')
const OUT_FILE = path.resolve(__dirname, '../src/config/templates.ts')
const STACK_SRC = path.resolve(__dirname, '../../invoke-admin/config/stack.json')
const STACK_DEST = path.resolve(__dirname, '../src/config/stack.json')
const SDK_CSPROJ = path.resolve(__dirname, '../../invoke-runtime/sdks/dotnet/Invoke.SDK/Invoke.SDK.csproj')
const SDK_NUPKG_OUT = path.resolve(__dirname, '../src/config/invoke-sdk-nupkg.ts')

function readDirRecursive(dir: string, base: string = dir): Record<string, string> {
  const result: Record<string, string> = {}
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      Object.assign(result, readDirRecursive(full, base))
    } else {
      const relativePath = path.relative(base, full).replace(/\\/g, '/')
      result[relativePath] = fs.readFileSync(full, 'utf8')
    }
  }
  return result
}

const templates: Record<string, Record<string, string>> = {}

for (const entry of fs.readdirSync(TEMPLATES_DIR, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue
  const templateDir = path.join(TEMPLATES_DIR, entry.name)
  templates[entry.name] = readDirRecursive(templateDir)
}

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-templates.ts — do not edit manually',
  '',
  'export const TEMPLATES: Record<string, Record<string, string>> = {'
]

for (const [templateName, files] of Object.entries(templates)) {
  lines.push(`  ${JSON.stringify(templateName)}: {`)
  for (const [filePath, content] of Object.entries(files)) {
    lines.push(`    ${JSON.stringify(filePath)}: ${JSON.stringify(content)},`)
  }
  lines.push(`  },`)
}

lines.push('}')
lines.push('')

fs.writeFileSync(OUT_FILE, lines.join('\n'))
console.log(`✅ Generated ${OUT_FILE} with ${Object.keys(templates).length} templates`)

// Copy stack.json from invoke-admin
fs.copyFileSync(STACK_SRC, STACK_DEST)
console.log(`✅ Copied stack.json from invoke-admin`)

// ── Build and embed the Invoke.SDK NuGet package ──────────────────────────────
const packOutDir = fs.mkdtempSync(path.join(os.tmpdir(), 'invoke-sdk-pack-'))
try {
  console.log('📦 Building Invoke.SDK NuGet package...')
  execSync(
    `dotnet pack "${SDK_CSPROJ}" -c Release -o "${packOutDir}" /p:RuntimeIdentifier= /p:PublishAot=false /p:EnableAotAnalyzer=false /p:EnableTrimAnalyzer=false`,
    { stdio: 'pipe' }
  )

  const nupkgFiles = fs.readdirSync(packOutDir).filter(f => f.endsWith('.nupkg'))
  if (nupkgFiles.length === 0) throw new Error('No .nupkg file produced by dotnet pack')

  const nupkgFilename = nupkgFiles[0]
  const nupkgPath = path.join(packOutDir, nupkgFilename)
  const nupkgBase64 = fs.readFileSync(nupkgPath).toString('base64')

  const sdkNupkgContent = [
    '// AUTO-GENERATED by scripts/generate-templates.ts — do not edit manually',
    '',
    `export const INVOKE_SDK_NUPKG_FILENAME = ${JSON.stringify(nupkgFilename)}`,
    `export const INVOKE_SDK_NUPKG_BASE64 = ${JSON.stringify(nupkgBase64)}`,
    ''
  ].join('\n')

  fs.writeFileSync(SDK_NUPKG_OUT, sdkNupkgContent)
  console.log(
    `✅ Embedded ${nupkgFilename} (${Math.round(fs.statSync(nupkgPath).size / 1024)}KB) into invoke-sdk-nupkg.ts`
  )
} finally {
  fs.rmSync(packOutDir, { recursive: true, force: true })
}
