import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quick-start',
        'getting-started/function-anatomy',
        'getting-started/deploying',
      ],
    },
  ],
  
  apiSidebar: [
    {
      type: 'category',
      label: 'Core APIs',
      items: [
        'api/globals',
        'api/request',
        'api/response',
        'api/kv-store',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {type: 'autogenerated', dirName: 'api/modules'},
      ],
    },
  ],
  
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/http-requests',
        'guides/file-serving',
        'guides/cryptography',
        'guides/environment-vars',
        'guides/websockets',
        'guides/compression',
        'guides/timers-async',
      ],
    },
  ],
  
  examplesSidebar: [
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/hello-world',
        'examples/rest-api',
        'examples/static-website',
        'examples/crypto-hashing',
        'examples/kv-store-usage',
        'examples/webhook-handler',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/limitations',
        'advanced/best-practices',
        'advanced/debugging',
      ],
    },
  ],
};

export default sidebars;
